
import Controladores.ControladorDoctores;
import Entidades.Medico;

/**
 *
 * @author Luis Eduardo Alvarado Celano
 * Carnet: 0900-20-7376
 * Ing. en Sistemas
 */
public class DoctorForm extends javax.swing.JFrame {

    /**
     * Creates new form DoctorForm
     */
    public DoctorForm() {
        initComponents();
        ControladorDoctores controller = new ControladorDoctores();
        jTable1.setModel(controller.verDoctores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDisponibilidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPrimerNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPrimerApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSegundoApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jhoraEntrada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jhoraSalida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTurnosMaximos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSexo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jEspecialidad = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 94, -1, -1));
        getContentPane().add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 86, 266, -1));

        jLabel2.setText("Especialidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 94, -1, -1));

        jLabel3.setText("Disponibilidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 147, -1, -1));
        getContentPane().add(jDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 139, 663, -1));

        jLabel4.setText("Primer Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 202, -1, -1));
        getContentPane().add(jPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 194, 663, -1));

        jLabel5.setText("Segundo Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 255, -1, -1));
        getContentPane().add(jSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 247, 663, -1));

        jLabel6.setText("Primer Apellido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 310, -1, -1));
        getContentPane().add(jPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 302, 663, -1));

        jLabel7.setText("Segundo Apellido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 363, -1, -1));
        getContentPane().add(jSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 355, 663, -1));

        jLabel8.setText("Celular");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 436, -1, -1));
        getContentPane().add(jCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 428, 236, -1));

        jLabel9.setText("Teléfono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 436, -1, -1));
        getContentPane().add(jTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 428, 257, -1));

        jLabel10.setText("Hora Entrada");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 489, -1, -1));
        getContentPane().add(jhoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 481, 236, -1));

        jLabel11.setText("Hora Salida");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 489, -1, -1));
        getContentPane().add(jhoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 481, 257, -1));

        jLabel12.setText("Turnos Mínimos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 540, -1, -1));
        getContentPane().add(jTurnosMaximos, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 532, 236, -1));

        jLabel13.setText("Sexo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 540, -1, -1));
        getContentPane().add(jSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 532, 257, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel14.setText("Datos del médico");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 64, 1700, 10));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 588, 122, -1));

        jButton2.setText("Grabar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 588, 122, -1));

        jPanel1.setBackground(new java.awt.Color(164, 243, 238));

        jEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neurocirujano", "Dermatologo", "Urologo", "Cardiologo", "Ginecologo", "Radiologo", "Farmacologo", "Oftalmologo" }));

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "ESPECIALIDAD", "DISPONIBILIDAD", "PRIMER NOMBRE", "SEGUNDO NOMBRE", "PRIMER APELLIDO", "SEGUNDO APELLIDO", "CELULAR", "TELEFONO", "HORA ENTRADA", "HORA SALIDA", "TURNOS MAXIMOS", "SEXO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(646, 646, 646)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1760, 680));

        jButton3.setText("Salir");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 628, 122, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jCodigo.setText("");
        jDisponibilidad.setText("");
        jPrimerNombre.setText("");
        jSegundoNombre.setText("");
        jPrimerApellido.setText("");
        jSegundoApellido.setText("");
        jCelular.setText("");
        jTelefono.setText("");
        jhoraEntrada.setText("");
        jhoraSalida.setText("");
        jTurnosMaximos.setText("");
        jSexo.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Medico medico = new Medico();
        ControladorDoctores controlador = new ControladorDoctores();
        medico.setlIntCodigo(Integer.parseInt(jCodigo.getText()));
        medico.setlStrEspecialidad(String.valueOf(jEspecialidad.getSelectedItem()));
        medico.setlStrDisponibilidad(jDisponibilidad.getText());
        medico.setlStrPrimerNombre(jPrimerNombre.getText());
        medico.setlStrSegundoNombre(jSegundoNombre.getText());
        medico.setlStrPrimerApellido(jPrimerApellido.getText());
        medico.setlStrSegundoApellido(jSegundoApellido.getText());
        medico.setlLongCelular(Long.parseLong(jCelular.getText()));
        medico.setlLongTelefono(Long.parseLong(jTelefono.getText()));
        medico.setlStrHoraEntrada(jhoraEntrada.getText());
        medico.setlStrHoraSalida(jhoraSalida.getText());
        medico.setlIntTurnosMaximos(Integer.parseInt(jTurnosMaximos.getText()));
        medico.setlStrSexo(jSexo.getText());
        
        controlador.CrearDoctor(medico); //controlador para crear un doctor
        jTable1.setModel(controlador.verDoctores());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jCelular;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JTextField jDisponibilidad;
    private javax.swing.JComboBox<String> jEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrimerApellido;
    private javax.swing.JTextField jPrimerNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSegundoApellido;
    private javax.swing.JTextField jSegundoNombre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jSexo;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTelefono;
    private javax.swing.JTextField jTurnosMaximos;
    private javax.swing.JTextField jhoraEntrada;
    private javax.swing.JTextField jhoraSalida;
    // End of variables declaration//GEN-END:variables
}
